<?php
$this->layout('../layouts/layout',[
    'title' => 'BAVentas | Categoria | Detalle'
]); 
?>

<?php $this->push('styles')?>
<?php $this->end()?>

<?php $this->start('contents')?>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>Categorias - Detalles</h1>
            <form action="<?= URL .'categoryid/save' ?>" method="post">
                <input type="text" name="categoryid" value="<?= $data->categoryid ?>">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="id_nombre">Nombre</label>
                            <input type="text" name="categoryname" id="id_nombre" class="form-control"
                            value="<?= $data->categoryname?>">
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="id_description">Descripción</label>
                            <input type="text" name="description" id="id_description" class="form-control"
                            value="<?= $data->description?>">
                        </div>
                    </div>
                </div>  
                <div class="row">
                    <div class="sol-sm-4">
                        <div class="form-group">
                            <input type="checkbox" name="estado" id="id_estado" class="form-check-input" <?= ($data->estado==1) ? 'checked' : '' ?>>
                            <label class="form-check-label" for="id_estado">Estado</label>
                        </div>
                    </div>
                    <div class="col-sm-8">

                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Guardar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php $this->stop() ?>

<?php $this->push('scripts')?>
<?php $this->end()?>