<?php
$this->layout('../layouts/layout',[
    'title' => 'BAVentas | Categoria'
]); 
?>

<?php $this->push('styles')?>
<?php $this->end()?>

<?php $this->start('contents')?>

<div class="container">
    <h1>Bienvenidos</h1>    
    <div class="row">
        <div class="col-sm-4">
            <a href="<?= URL . 'categoria/detail'?>" class="btn btn-primary btn-block">Nuevo</a>
        </div>
    </div>
    <br>    
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10%;" >ID</th>
                        <th style="width: 30%;" >NOMBRE</th>
                        <th style="width: 50%;" >DESCRIPCION</th>
                        <th style="width: 10%;" ></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data as $row): ?>
                        <tr>
                            <td><?= $row->categoryid ?></td>
                            <td><?= $row->categoryname ?></td>
                            <td><?= $row->description ?></td>
                            <td>
                                <a href="<?= URL . "categoria/detail/{$row->categoryid}" ?>" class="btn btn-success btn-sm"><i class="fa fa-pencil"></i></a>
                                <a href="<?= URL . "categoria/delete/{$row->categoryid}" ?>" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <br>    
</div>


<?php $this->stop() ?>

<?php $this->push('scripts')?>
<?php $this->end()?>