<?php
$this->layout('../layouts/layout',[
    'title' => 'BAVentas | Inicio'
]); 
?>

<?php $this->push('styles')?>
<?php $this->end()?>

<?php $this->start('contents')?>

<div class="container">
    <?php echo env('DB_DATABASE', 'Hola')?>

    <h1>BAVentas | Bienvenidos</h1>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt possimus, dolorum, consectetur laborum
        recusandae nesciunt, fuga hic dolore tempore corrupti neque similique amet corporis totam aperiam iusto ut cum
        ex.</p>
</div>
<?php $this->stop() ?>

<?php $this->push('scripts')?>
<?php $this->end()?>