<?php
$this->layout('../layouts/layout',[
    'title' => 'BAVentas | Prueba'
]); 
?>

<?php $this->push('styles')?>
<?php $this->end()?>

<?php $this->start('contents')?>
<div class="container">
    <h1>Pagina de pruebas</h1>
    <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Deserunt possimus, dolorum, consectetur laborum
        recusandae nesciunt, fuga hic dolore tempore corrupti neque similique amet corporis totam aperiam iusto ut cum
        ex.</p>
    <?php $this->stop() ?>
</div>


<?php $this->push('scripts')?>
<?php $this->end()?>